default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_POOL', 5) %>
  host: <%= ENV.fetch('DB_HOST', 'postgres') %>
  port: 5432
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>

development:
  <<: *default
  database: excavatorr_development

test:
  <<: *default
  database: excavatorr_test

production:
  <<: *default
  database: excavatorr_production
  username: excavatorr
  password: <%= ENV['EXCAVATORR_DATABASE_PASSWORD'] %>
